version: '3.3'

services:

  php-fpm:
    build:
      context: ./images/php
      dockerfile: Dockerfile
      args:
        TIMEZONE_CUSTOM: 'Europe/Kiev'
    ports:
      - '9000:9000'
    links:
      - postgresql
    volumes:
      - ../:/app
      - ./config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
#change of date.timezone with file unlike the server
#      - ./config/php.ini:/usr/local/etc/php/php.ini
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    working_dir: /app
    networks:
      - app-tier
    container_name: 'php-fpm'

  nginx:
    image: nginx:1.16.1-alpine
    restart: on-failure
    links:
      - php-fpm
      - postgresql
    container_name: 'nginx'
    working_dir: /app
    ports:
      - '80:80'
    volumes:
      - ../:/app
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - app-tier
  postgresql:
    image: postgres:10-alpine
    ports:
      - '5432:5432'
    container_name: 'postgresql'
    working_dir: /app
    restart: always
    environment:
      POSTGRES_DB: 'db_name'
      POSTGRES_USER: 'db_user'
      POSTGRES_PASSWORD: 'db_pass'
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    networks:
      - app-tier
networks:
  app-tier:
    driver: bridge